export const MENU_SIDER_HANDLER = "MENU_SIDER_HANDLER";
export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";
export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_MORE_POKEMONS = "GET_MORE_POKEMONS";
export const GET_MORE_POKEMONS_SUCCESS = "GET_MORE_POKEMONS_SUCCESS";
export const GET_MORE_POKEMONS_ERROR = "GET_MORE_POKEMONS";
